### PR TITLE
Dockerize opencve

### PR DESCRIPTION
**Pull request by lucmichalski**
- Added dockerfile alpine based with multi-stage build
- Added docker-compose file
- Added .env file for compose and build arguments
- Secured docker container by using non-root user

### CODE REVIEW

**Comment by ldurnez** [comment]
Thank you for your PR, it's nice to you to contribute to OpenCVE !
However we think we can make it more KISS. To be honest, I already prepared a branch to add docker support, and the diff is huge between yours and mine :). Stay tuned for it.

Could you please :
- keep it KISS (no external code dependencies, no need to build it, you can pip install opencve directly, it's available!, we prefer debian-slim image as well, use 1 config file, ...),
- use the maintainer to "OpenCVE community <dev@opencve.io>",
- squash your commits,
- add a documentation in the README file

We will add a CONTRIBUTING to help you for the next PRs!
Thanks !

**Comment by lucmichalski** [comment]
I ll let you do you your way, I ll use my fork ^^

**Comment by ncrocfer** [comment]
As directly seen with @lucmichalski in private discussion he currently works on a personal project and he has no time to do the changes (squash the commits, fix bad copy-paste, create the documentation....) or maintain the image later.

We close this PR and we'll create another one with these prerequisites.

**Comment by reg0bs** [comment]
I just wanted to go the same route to build a docker image and test it in k8s.
If you have a version to test I would be happy to help and run it in a cluster.
I can also offer to build manifests as templates if that is of help for future k8s users.
Thanks!

**Pull request closed without merging**
