### PR TITLE
Add tags in dashboard

### LINKED ISSUE #166: Tags improvement
Hello,

First of all thanks for providing us this amazing tool.

I would suggest an improvement on tagging. It would be very convenient to be able to see the tags set on CVEs in the dashboard view in the same way we see `vendors` and `products`. Also another idea would be able to automatically add tags to subscribed CPE/CWE.

Let me give a bit more context.
I would like to make sure all CVEs I subscribed are read and acknowledged by my team. Easiest way I see would be to either add an `Unread` tag on all incoming CVE and then put an `Acknowledged` after checking it.

But it is a bit of a pain to have to click on each CVE to see which tags are set.

Be able to set tags on multiple CVE from the dashboard would be nice as well.

Regards

### PR DESCRIPTION
**Pull request by cva-nbs**
Partially resolve #166 as it add tags in the dashboard view. But it still needs the part where a tag is automatically added when an event is triggered on a subscribed CVE

### CODE REVIEW

**Review by ncrocfer — CHANGES_REQUESTED** [review]
Hi @cva-nbs ,

First of all thanks for this pull-request ! However I'm a bit annoying for 2 points, here are my comments.

## Style
The final rendering is a bit *broken*, you add a new column in a small table. Here are 2 screenshots, you can see the output is too compacted:

**Before**
image

**After**
image

I'm not fan with the new format. I think you can use the `timeline-footer` class of the AdminLTE template: https://adminlte.io/themes/AdminLTE/pages/UI/timeline.html (not tested the result, to try).

And can you please remove the commas for the tags `_type`? Rendering will be improved too.

## Performance

You call `tag = UserTag.query.filter_by(user_id=current_user.id, name=obj).first()` for each object in the list, so for each tag for each change.

Imagine the following settings:
- a pagination of 20 changes in the homepage (this is the default setting), 
- a limit of 3 objects in the excerpt function (default setting too)

We can potentially increase the number of database requests of **60 queries** ! Just with default settings. This is not acceptable for performance (even if it's not big queries).

The solution is to provide a global JSON variable in the HTML and load a dictionnary of the tags and their associated color only once, at the very beginning.

Do you think you can provide that? If not this 2nd comment is optional, I'm ok to do it in another PR ;)

PS: can you also use `black` to pass the linter? See this check: https://github.com/opencve/opencve/pull/167/checks

**Comment by cva-nbs** [comment]
I will try to implement `timeline-footer` and see if the presentation is better. I will let you know ASAP
To be honest I don't see at all how to implement the optimization you proposed so I will let it for you to be done in another

**Comment by cva-nbs** [comment]
As far as my tests go I don't see a difference using the timeline footer for the table.

A possibility could be to put the tags in a div under the table `vendor/products` and then maybe don't make them go through the `tags_excerpt` so they can all be shown ( I don't see people putting that many tags that the design will break). 

Another one could be to put the tags in the top of the CVE name near the time of last update 

image

**Comment by ncrocfer** [comment]
Why do you include them in the header? Sorry it's just my opinion, but I don't find this rendering very beautiful :worried:

Just use the `timeline-footer`, or add a new table below the Vendors/Products one:

Capture d’écran 2022-01-08 à 12 28 35

Don't forget this idea of this homepage is to quickly display changes, in a beautiful way (at least I try ^^). So I don't want to add a lot of information in it (that's why we'll not add references, CPE, CWE...). If user wants more information he clicks on the CVE link.

So I'm ok to add the tags list, but please display it in a *beautiful* way (I'm not a webdesign expert, so I just want an acceptable UI 😉 ). For instance don't display an empty table in the CVE hasn't associated tags.

**Review by ncrocfer — APPROVED** [review]

**Pull request merged**
