### PR TITLE
tests: added test for admin 

### PR DESCRIPTION
**Pull request by varunnm17**
Hello, I am interested in working on this OpenCVE project. I wrote these tests to learn more about the project in seeing how it works on a deeper level, and I also wanted to increase the coverage for the admin file. I have made these changes with Unit Tests for Admin that target making changes to passwords based on the existence of a user instance. I appreciate the opportunity to work on this project and hopefully contribute more.

### CODE REVIEW

**Comment by ncrocfer** [comment]
Hi @varunnm17, thank you for this PR.

It's cool to start adding tests about the admin part of OpenCVE. I just have 2 comments before approve your PR:

- you test the `UserModelView.on_model_change` function, can you also test if the `email_confirmed_at` attribute has been changed ? You can use the `freezer` fixture, something like this:

```python
freezer.move_to("2021-01-01")
assert user.email_confirmed_at.strftime("%Y-%m-%d") == "2021-01-01"
```

- As a developer I really like comments, but comments should be kept concise as possible, and it's not the case in your PR. For example you explain in your docstring what you do just below: *I needed to create a user and pass in the user to the form in order to create data points. I call the function with the associated parameters[...]*.  Moreover you made a bad copy paste in the second test (*[...] when the user is created [...]*).

You can just remove all your comments please, the code is simple to understand, no need long comments for that ;)

**Review by ncrocfer — CHANGES_REQUESTED** [review]
Feedbacks have been given in the previous message (remove the comments + test the `email_confirmed_at` attribute).

**Comment by MichaelPereira** [comment]
I will take the blame for the comments part, I'm not familiar enough with the codebase/framework myself to understand what was being tested exactly and asked @varunnm17 for clarifying comments before the PR was submitted in fear that others might be confused as well.

**Comment by varunnm17** [comment]
Thank you for your comments @ncrocfer. I just made the changes that you requested for in the new commit.

**Review by ncrocfer — APPROVED** [review]

**Pull request merged**
