### PR TITLE
Show subscribed users for vendors and products

### PR DESCRIPTION
**Pull request by gitmopp**
See #182
It is not pefect as the names are shown as "<User xyz>"

### CODE REVIEW

**Review by ncrocfer — APPROVED** [review]

**Comment by ncrocfer** [comment]
@gitmopp ok for me, can you please run `black` to pass the checks please? I will be able to merge it :)

**Comment by gitmopp** [comment]
What is wrong with the lint test?

**Comment by ncrocfer** [comment]
It fails. See https://github.com/opencve/opencve/runs/5432081844?check_suite_focus=true

**Comment by gitmopp** [comment]
Sorry, I don't understand the problem

**Comment by ncrocfer** [comment]
No problem, I think it's because you don't know what **Github Actions** or **Black** :)

- **Black** is a linter, it formats the code so you don't have to worry about conventions. More information here: https://github.com/psf/black
- **Github Actions** is the CI/CD of Github, it's possible for instance to launch the tests when a new PR is created. More information here: https://docs.github.com/en/actions

OpenCVE uses Github Actions for lint & tests. The code is here: https://github.com/opencve/opencve/blob/master/.github/workflows/tests.yml

In this file you can see the `black` command is used to check the format of the code:

image

When you created your PR this command has been executed. And we can see in the logs of Github Actions that your PR is not compliant with Black:

image

So I can not merge it properly (see the red cross):

image

It does not mean your PR is not valid, it just says that the format is not compliant with Black. It's a convention I want to keep to have a proper base code.

The solution is just to execute `black` on your side, git push your changes and the tests will pass.

Is-it ok for you?

**Review by ncrocfer — APPROVED** [review]

**Pull request merged**
