### PR TITLE
Improved search functionality on /cve

### PR DESCRIPTION
**Pull request by M0dEx**
#### Changes
- the search function now searches for a matching CVE ID, vendor or a
  product
- searching in the description has also been made case-insensitive

All in all, the changes result in increased accuracy of the results ~~without adding a noticeable amount of delay to the searches.~~

### CODE REVIEW

**Comment by M0dEx** [comment]
Sorry for that, the commit I reverted was meant for a different repo.

**Comment by ncrocfer** [comment]
Hi @M0dEx ,

First of all thanks for this PR, it's really appreciated and it will now be much more practical for users to search into the database!

I tested your feature and it works perfectly well, I just have 2 remarks:

- why do you remove spaces in vendor name and replace them by underscores in the product name ? Maybe I'm wrong but can you simply keep spaces ? The code will stay KISS, and if the user will search `foo bar`, the vendor and product objects will just return `None`.
- I have problems with performance, the query is now **>800ms** (sometimes it was **>1s** during my tests) : opencve_sql_perf

The latency is produced by the following code:

```python
query = query.filter(or_(
    Cve.cve_id.contains(args.get('search')),
    Cve.summary.ilike(f"%{args.get('search')}%"),
    Cve.vendors.contains([vendor.name]) if vendor else None,
    Cve.vendors.contains([product.name]) if product else None
))
```

I think we miss indexes here, for example to support the `ilike` operator we can use a GIN index:

```sql
> SELECT * FROM cves WHERE summary ILIKE '%foo%';
Time: 687,210 ms
> CREATE EXTENSION pg_trgm;
> CREATE INDEX ix_cves_summary ON cves USING gin (summary gin_trgm_ops);
> SELECT * FROM cves WHERE summary ILIKE '%foo%';
Time: 16,377 ms
```

An index already exists on the `cve_id` column, we need to change it:

```sql
> DROP INDEX ix_cves_cve_id;
> CREATE INDEX ix_cves_cve_id ON cves USING gin (cve_id gin_trgm_ops);
```

These 2 indexes fix the performance issue: 
opencve_sql_perf_2

BUT:
1. we add a new dependency (the need for the user to enable the  `pg_trgm` extension). I'm not sure if it's a real problem, your feature is useful to easily search in OpenCVE database, it's not *very* difficult to enable a PostgreSQL extension. Plus this module seems common, and easily installable (https://dba.stackexchange.com/a/165301).
2. I don't know the impact for INSERT/UPDATE queries (when a new CVE is created or changed). I think it's ok because the NVD does not continuously update the CVEs list. But I'm not sure, we still need to benchmark this to avoid impacting the users during the synchronization task :)

Let me quickly check that, I will write here with the results of the benchmark (or if you or someone else already knows the answer it I take it ^^).

PS: can you please run `black` on your code ? The linter failed (https://github.com/opencve/opencve/pull/97/checks).

**Comment by M0dEx** [comment]
### Formatting of vendor and product names
> why do you remove spaces in vendor name and replace them by underscores in the product name ? Maybe I'm wrong but can you simply keep spaces ? The code will stay KISS, and if the user will search foo bar, the vendor and product objects will just return None.

Well, the vendors in the DB are usually (if not always) stored without spaces in their names, so not removing the spaces in case of vendors like `Trend Micro`, `Check Point`, etc. misses some CVEs and doesn't return the respective vendors as the `Vendor`.
Same goes for products like `Interscan Web Security Virtual Appliance`.

I agree it makes the code look a bit junky, but IMO it is necessary. 

### Database performance
While I do agree that `ilike` adds some dependencies and requires a few changes, which can be somewhat annoying to all the people already running OpenCVE, it also makes the search results much more accurate. 
Whether it's a trade-off worth pursuing is up to you guys.

**Comment by ncrocfer** [comment]
Ok it's very clear, let's keep this convention for vendors and products 👍 

Concerning the **ilike** search on `cve_id` and `summary` I think it's a very useful feature, so I'm ok to introduce a new requirement. In fact it's not so complicated to be compliant : the **pg_trgm** is trusted from PG13, and before that it just requires the `CREATE EXTENSION` privilege.

As you see I created a new commit on your PR, with the associated migration, but tests fail because they don't use the migrations to create the database but only the `db.create_all()` command... Not a problem, I will change that before merging this PR ;)

**Review by ncrocfer — APPROVED** [review]

**Pull request merged**
